var elixir = require('laravel-elixir');

elixir(function (mix) {

    mix.styles([
        "../../../public/template/img/favicon.ico",
        "../../../public/template/css/bootstrap.min.css",
        "../../../public/template/css/font-awesome.min.css",
        "../../../public/template/css/owl.carousel.css",
        "../../../public/template/css/owl.theme.css",
        "../../../public/template/css/owl.transitions.css",
        "../../../public/template/css/animate.css",
        "../../../public/template/css/normalize.css",
        "../../../public/template/css/meanmenu.min.css",
        "../../../public/template/css/main.css",
        "../../../public/template/css/educate-custon-icon.css",
        // "../../../public/template/css/morrisjs/morris.css",
        "../../../public/template/css/scrollbar/jquery.mCustomScrollbar.min.css",
        "../../../public/template/css/metisMenu/metisMenu.min.css",
        "../../../public/template/css/metisMenu/metisMenu-vertical.css",
        "../../../public/template/css/calendar/fullcalendar.min.css",
        "../../../public/template/css/calendar/fullcalendar.print.min.css",
        "../../../public/template/css/data-table/bootstrap-table.css",
        "../../../public/template/css/data-table/bootstrap-editable.css",
        "../../../public/template/css/tabs.css",
        "../../../public/template/css/form/all-type-forms.css",
        "../../../public/template/css/dropzone/dropzone.css",
        "../../../public/template/css/datapicker/datepicker3.css",
        "../../../public/css/educa-custom.css",
        "../../../public/css/educa-custom-menu.css",
        "../../../public/template/css/modals.css",
        "../../../public/template/style.css",
        "../../../public/template/css/responsive.css",
        // "../../../public/css/app.css",
    ], 'public/css/production.dist.min.css');

    mix.scripts([
        '../../../public/template/js/vendor/modernizr-2.8.3.min.js',
        '../../../public/template/js/vendor/jquery-1.12.4.min.js',
        '../../../public/template/js/bootstrap.min.js',
        '../../../public/template/js/wow.min.js',
        '../../../public/template/js/jquery-price-slider.js',
        '../../../public/template/js/jquery.meanmenu.js',
        '../../../public/template/js/owl.carousel.min.js',
        '../../../public/template/js/jquery.sticky.js',
        '../../../public/template/js/jquery.scrollUp.min.js',
        '../../../public/template/js/counterup/jquery.counterup.min.js',
        '../../../public/template/js/counterup/waypoints.min.js',
        '../../../public/template/js/counterup/counterup-active.js',
        '../../../public/template/js/scrollbar/jquery.mCustomScrollbar.concat.min.js',
        '../../../public/template/js/scrollbar/mCustomScrollbar-active.js',
        '../../../public/template/js/metisMenu/metisMenu.min.js',
        '../../../public/template/js/metisMenu/metisMenu-active.js',
        '../../../public/template/js/data-table/bootstrap-table.js',
        '../../../public/template/js/data-table/tableExport.js',
        '../../../public/template/js/data-table/data-table-active.js',
        '../../../public/template/js/data-table/bootstrap-table-editable.js',
        '../../../public/template/js/data-table/bootstrap-editable.js',
        '../../../public/template/js/data-table/bootstrap-table-resizable.js',
        '../../../public/template/js/data-table/colResizable-1.5.source.js',
        '../../../public/template/js/data-table/bootstrap-table-export.js',
        // '../../../public/template/js/morrisjs/raphael-min.js',
        // '../../../public/template/js/morrisjs/morris.js',
        // '../../../public/template/js/morrisjs/morris-active.js',
        // '../../../public/template/js/sparkline/jquery.sparkline.min.js',
        // '../../../public/template/js/sparkline/jquery.charts-sparkline.js',
        // '../../../public/template/js/sparkline/sparkline-active.js',
        '../../../public/template/js/calendar/moment.min.js',
        // '../../../public/template/js/calendar/fullcalendar.min.js',
        // '../../../public/template/js/calendar/fullcalendar-active.js',
        '../../../public/template/js/datapicker/bootstrap-datepicker.js',
        '../../../public/template/js/datapicker/datepicker-active.js',
        '../../../public/template/js/tab.js',
        '../../../public/template/js/plugins.js',
        '../../../public/template/js/main.js',
        // '../../../public/template/js/tawk-chat.js',
        '../../../public/js/custom_educa.js',
        '../../../public/js/app.js',
    ], 'public/js/production.dist.min.js');
});
